# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compressUtl.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 440)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 49, 980, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.jsRadio = QtWidgets.QRadioButton(self.groupBox)
        self.jsRadio.setEnabled(True)
        self.jsRadio.setGeometry(QtCore.QRect(150, 10, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.jsRadio.setFont(font)
        self.jsRadio.setChecked(True)
        self.jsRadio.setObjectName("jsRadio")
        self.cssRadio = QtWidgets.QRadioButton(self.groupBox)
        self.cssRadio.setGeometry(QtCore.QRect(450, 20, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cssRadio.setFont(font)
        self.cssRadio.setObjectName("cssRadio")
        self.spriteRadio = QtWidgets.QRadioButton(self.groupBox)
        self.spriteRadio.setGeometry(QtCore.QRect(750, 14, 100, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spriteRadio.setFont(font)
        self.spriteRadio.setObjectName("spriteRadio")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 98, 400, 97))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.fileRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.fileRadio.setGeometry(QtCore.QRect(100, 20, 89, 22))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileRadio.setFont(font)
        self.fileRadio.setChecked(True)
        self.fileRadio.setObjectName("fileRadio")
        self.dirRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.dirRadio.setGeometry(QtCore.QRect(100, 60, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dirRadio.setFont(font)
        self.dirRadio.setObjectName("dirRadio")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 90, 980, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 7, 980, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 980, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 194, 980, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(408, 99, 3, 95))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.choiseFileDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.choiseFileDirBtn.setGeometry(QtCore.QRect(429, 112, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choiseFileDirBtn.setFont(font)
        self.choiseFileDirBtn.setObjectName("choiseFileDirBtn")
        self.choiseRstLabel = QtWidgets.QLabel(self.centralwidget)
        self.choiseRstLabel.setEnabled(False)
        self.choiseRstLabel.setGeometry(QtCore.QRect(530, 112, 451, 70))
        self.choiseRstLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.choiseRstLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.choiseRstLabel.setWordWrap(True)
        self.choiseRstLabel.setObjectName("choiseRstLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 201, 91, 30))
        self.label_3.setObjectName("label_3")
        self.outputDirInput = QtWidgets.QTextEdit(self.centralwidget)
        self.outputDirInput.setEnabled(True)
        self.outputDirInput.setGeometry(QtCore.QRect(195, 202, 671, 30))
        self.outputDirInput.setObjectName("outputDirInput")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 240, 980, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.compressBtn = QtWidgets.QPushButton(self.centralwidget)
        self.compressBtn.setGeometry(QtCore.QRect(350, 273, 280, 40))
        self.compressBtn.setObjectName("compressBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(350, 355, 80, 30))
        self.label_4.setObjectName("label_4")
        self.compressProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.compressProgressBar.setEnabled(True)
        self.compressProgressBar.setGeometry(QtCore.QRect(430, 359, 200, 23))
        self.compressProgressBar.setProperty("value", 24)
        self.compressProgressBar.setObjectName("compressProgressBar")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setEnabled(True)
        self.line_6.setGeometry(QtCore.QRect(10, 50, 3, 190))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setEnabled(True)
        self.line_7.setGeometry(QtCore.QRect(990, 50, 3, 190))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.outputDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.outputDirBtn.setGeometry(QtCore.QRect(890, 202, 75, 30))
        self.outputDirBtn.setObjectName("outputDirBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        # 手动编写的代码
        self.choiseRstLabel.hide()
        self.jsRadio.clicked.connect(MainWindow.changeFileKind)
        self.cssRadio.clicked.connect(MainWindow.changeFileKind)
        self.spriteRadio.clicked.connect(MainWindow.changeFileKind)
        self.fileRadio.clicked.connect(MainWindow.changeFileKind)
        self.dirRadio.clicked.connect(MainWindow.changeFileKind)

        self.choiseFileDirBtn.clicked.connect(MainWindow.choiseFileOrDir)
        self.outputDirBtn.clicked.connect(MainWindow.choiseOutputDir)
        self.compressBtn.clicked.connect(MainWindow.beginCompress)

        self.label_4.hide()
        self.compressProgressBar.hide()

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Compress Tool"))
        self.jsRadio.setText(_translate("MainWindow", "Js"))
        self.cssRadio.setText(_translate("MainWindow", "Css"))
        self.spriteRadio.setText(_translate("MainWindow", "image"))
        self.fileRadio.setText(_translate("MainWindow", "文件"))
        self.dirRadio.setText(_translate("MainWindow", "文件目录"))
        self.label.setText(_translate("MainWindow", "Compress File Tool"))
        self.choiseFileDirBtn.setText(_translate("MainWindow", "选择"))
        self.choiseRstLabel.setText(_translate("MainWindow", "选择的文件：ssssssssssssssssssssssssss"))
        self.label_3.setText(_translate("MainWindow", "输入输出路径:"))
        self.compressBtn.setText(_translate("MainWindow", "开始压缩"))
        self.label_4.setText(_translate("MainWindow", "完成百分比："))
        self.outputDirBtn.setText(_translate("MainWindow", "打开"))

